// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLF23qtrvMgsy6BFoFRWonpm7KWeUTSW4',
    appId: '1:915782805180:web:e18ad9b7903e782b0192b9',
    messagingSenderId: '915782805180',
    projectId: 'safechat-prod-66143',
    authDomain: 'safechat-prod-66143.firebaseapp.com',
    storageBucket: 'safechat-prod-66143.firebasestorage.app',
    measurementId: 'G-RLQB5RV34G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu-eeJ0azFUxYopIxeuKH1vHCVez1y--k',
    appId: '1:915782805180:android:99f320a7da4387a10192b9',
    messagingSenderId: '915782805180',
    projectId: 'safechat-prod-66143',
    storageBucket: 'safechat-prod-66143.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJi25JO85W9xwBaGRqEhOzlHJ_Y43Lbc',
    appId: '1:915782805180:ios:c034a62bc6f635680192b9',
    messagingSenderId: '915782805180',
    projectId: 'safechat-prod-66143',
    storageBucket: 'safechat-prod-66143.firebasestorage.app',
    iosBundleId: 'com.safechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWJi25JO85W9xwBaGRqEhOzlHJ_Y43Lbc',
    appId: '1:915782805180:ios:c034a62bc6f635680192b9',
    messagingSenderId: '915782805180',
    projectId: 'safechat-prod-66143',
    storageBucket: 'safechat-prod-66143.firebasestorage.app',
    iosBundleId: 'com.safechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLF23qtrvMgsy6BFoFRWonpm7KWeUTSW4',
    appId: '1:915782805180:web:02a9a9a85547ea550192b9',
    messagingSenderId: '915782805180',
    projectId: 'safechat-prod-66143',
    authDomain: 'safechat-prod-66143.firebaseapp.com',
    storageBucket: 'safechat-prod-66143.firebasestorage.app',
    measurementId: 'G-DKWLTG7DCE',
  );
}
