// File generated by FlutterFire CLI placeholder.
// You must run `flutterfire configure` to generate the actual options.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: '1:placeholder:web:placeholder',
    messagingSenderId: 'placeholder',
    projectId: 'safechat-prod',
    authDomain: 'safechat-prod.firebaseapp.com',
    storageBucket: 'safechat-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: '1:placeholder:android:placeholder',
    messagingSenderId: 'placeholder',
    projectId: 'safechat-prod',
    storageBucket: 'safechat-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: '1:placeholder:ios:placeholder',
    messagingSenderId: 'placeholder',
    projectId: 'safechat-prod',
    storageBucket: 'safechat-prod.firebasestorage.app',
    iosBundleId: 'com.safechat.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: '1:placeholder:ios:placeholder',
    messagingSenderId: 'placeholder',
    projectId: 'safechat-prod',
    storageBucket: 'safechat-prod.firebasestorage.app',
    iosBundleId: 'com.safechat.app',
  );
}
