import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Resolves an image URL for use in CachedNetworkImage.
///
/// The bucket is private. All GCS media URLs delivered by the backend are
/// already short-lived signed download URLs (generated by sign_media_url on
/// the backend). This provider just passes them through.
/// External URLs (Google avatar CDN, etc.) are also passed through unchanged.
final firebaseImageUrlProvider = FutureProvider.family<String, String>((ref, rawUrl) async {
  if (rawUrl.isEmpty) return '';
  // All https:// URLs — whether signed GCS download URLs or external CDN URLs —
  // are valid HTTP GET targets and can be used directly.
  if (rawUrl.startsWith('https://')) return rawUrl;
  // Fallback: discard any non-http URL rather than crashing the widget tree.
  throw Exception('Unsupported image URL scheme: $rawUrl');
});
